spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_question_data?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6380
      database: 0
      password: 123456
      lettuce:
        pool:
          max-active: 8 # 最大连接
          max-idle: 8 # 最大空闲
          min-idle: 0 # 最小空闲
          max-wait: 100 # 最大等待时间(毫秒)
  application:
    name: AnswerQuestionServerChild
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规则
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql日志
  mapper-locations: classpath*:mapper/*.xml # 扫描mapper xml文件
  type-aliases-package: com.smileshark.entity # 别名包
springdoc:
  api-docs:
    enabled: true # 开启swagger文档
    path: /v3/api-docs # 配置swagger文档的数据访问路径
  swagger-ui:
    path: /swagger-ui.html # 访问swagger文档的路径
mysql:
  data:
    split:
      string: LBT_1534_LX_5212_WZL_4818
school:
  times:
    STUDENT_EXAM_MAX_TIMES: 3
  url:
    STUDENT_LOGIN_URL: https://ai.cqzuxia.com/connect/token
    STUDENT_INFO_URL: https://ai.cqzuxia.com/education/api/Student/GetStudentInfo
    STUDENT_HAVE_COURSE_URL: https://ai.cqzuxia.com/evaluation/api/stuevaluatereport/GetCourseProgram
    STUDENT_GET_COURSE_INFO_URL: https://ai.cqzuxia.com/evaluation/api/studentevaluate/GetCourseInfoByCourseId
    STUDENT_SUBSECTION_EXAM_START_URL: https://ai.cqzuxia.com/evaluation/api/studentevaluate/beginevaluate
    STUDENT_SUBSECTION_ANSWER_QUESTION_URL: https://ai.cqzuxia.com/evaluation/api/StudentEvaluate/SaveEvaluateAnswer
    STUDENT_SUBSECTION_EXAM_END_URL: https://ai.cqzuxia.com/evaluation/api/StudentEvaluate/SaveTestMemberInfo
    STUDENT_MISTAKES_URL: https://ai.cqzuxia.com/evaluation/api/StuCenter/GetFaultQuestionList

    TEACHER_LOGIN_URL: https://zxsz.cqzuxia.com/connect/token
    TEACHER_INFO_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCenter/GetTeacherInfo
    TEACHER_TEST_EXAM_START_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCourseEvaluate/GetTeacherCourseExamInfoByCourseID
    TEACHER_TEST_EXAM_ANSWER_QUESTION_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCourseEvaluate/SaveTeacherCourseExamQuestion
    TEACHER_TEST_EXAM_END_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCourseEvaluate/SaveTeacherCourseExamInfo
    TEACHER_PASS_SUBSECTION_EXAM_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCourseEvaluate/GetTeacherCourseEvaluateCompleteTree
    TEACHER_SUBSECTION_EXAM_START_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCourseEvaluate/GetQuesionListByKPId
    TEACHER_SUBSECTION_EXAM_END_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCourseEvaluate/SaveTeacherCourseEvaluateInfo
    TEACHER_TEST_EXAM_RECORD_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCourseEvaluate/GetTeacherCourseExamRecordList
    TEACHER_TEST_EXAM_FINISH_INFO_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/TeacherCourseEvaluate/GetQuestionListByTeacherCourseExamID
    TEACHER_COURSE_LIST_URL: https://zxsz.cqzuxia.com/teacherCertifiApi/api/CourseChapter/GetLessonListByCondition

  params:
    STUDENT_CLIENT_ID: 43215cdff2d5407f8af074d2d7e589ee
    STUDENT_CLIENT_SECRET: DBqEL1YfBmKgT9O491J1YnYoq84lYtB/LwMabAS2JEqa8I+r3z1VrDqymjisqJn3
    TEACHER_CLIENT_ID: c12abe723eda4b66af77015f2b572440
    TEACHER_CLIENT_SECRET: yHpq/AII2pBeUrUlSeMZhEs84gxSfQ/y+PyGBOmI6dh33EK6Za1VwHwz7uRRifUC
    MISTAKES_MAX_COUNT: 2000
key:
  token:
    key: smileshark&${mysql.data.split.string}
    expiration-time: 43200